### ISSUE TITLE
Request for Specific Dependency Versions to Resolve Mismatches

### ISSUE THREAD

**Issue by ranyrz** [wagner-group/MarkMyWords#3]
Hey! Ran into a bit of a snag trying to get the code running due to some dependency version mismatches. 
Could you guys share the exact versions of all dependencies used? 

Would really help me out!

**Comment by julien-piet** [comment]
Hi! Thanks for reaching out. I won't be able to check those this week, but I wanted to acknowledge your message, and I will be looking into this asap. 

In the mean time, would you mind sharing the dependencies that are creating an issue? And which version of Python you are using? Thanks!
