### ISSUE TITLE
Inquiry on Source and Generator Code for the provided Huffman Encodings 

### ISSUE THREAD

**Issue by zenquiorra** [wagner-group/MarkMyWords#4]
Hi there,

I noticed the Huffman Encodings for Llama2 and Mistral are included here. Could you please clarify if these were obtained from an external source? I'm interested in finding Huffman encodings for other models, such as GPT-2.

If these encodings were created internally, would it be possible to share the code used to generate them? Specifically, I'm interested in adding a preprocessing function for this purpose to the existing repository.

Thank you!

**Comment by julien-piet** [comment]
Hi,

Thanks for reaching out! You can find the code for generating Huffman encodings in `https://github.com/wagner-group/MarkMyWords/blob/main/src/watermark_benchmark/utils/bit_tokenizer.py`.

This is also accessible using command `watermark-benchmark-generate-huffman`, with syntax:

```
watermark-benchmark-generate-huffman tokenizer_path corpus_path output_path
```
where:
* `tokenizer_path` is the path to the tokenizer (or the hugging face name of the tokenizer)
*  `corpus_path` is the path to a folder containing a corpus of textual data. The expected data format is one or multiple json files in the folder, each containing arrays of strings. 
* `output_path` is the write path for the encoding

We used a large set of random English wikipedia articles to generate our encoding.
